//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssestsRequest
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Assest { get; set; }
        public decimal Quantity { get; set; }
        public bool HasRejected { get; set; }
        public bool HasApproved { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusChangedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
