//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AssestsRequests = new HashSet<AssestsRequest>();
            this.Requests = new HashSet<Request>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string AuthString { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string BCHash { get; set; }
        public string NickName { get; set; }
        public Nullable<decimal> PV { get; set; }
        public Nullable<bool> PVUpdaterStatus { get; set; }
        public string Criteria { get; set; }
        public Nullable<decimal> CriteriaValue { get; set; }
        public bool IsSearchable { get; set; }
        public bool IsSuperAdmin { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDataActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssestsRequest> AssestsRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
